# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 766f2f73a392c6bbbcb7d55fcdb53cecccc0acd1fb5ec64e2d181adfb5d208c2fe23421510524806b2b3ff2201b761071505e9aed96c96303ac8676b07e79519

test:
  secret_key_base: 9e8919286bfbf74619f6d569cdfd378c55eadb6d8223069e659b6da2bcb49dbda56f87ba76a25ab39825ad498f9941a68a731ca521a74f4e755a77f4e262469d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
